spring:
  datasource:
    url: jdbc:h2:~/codechobo
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug
    org.springframework.web: debug
