spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/codechobo
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug
    org.springframework.web: debug
