apiVersion: apps/v1
kind: Deployment
metadata:
  name: codechobo
spec:
  selector:
    matchLabels:
      app: codechobo
  template:
    metadata:
      labels:
        app: codechobo
    spec:
      containers:
      - name: codechobo
        image: govlmo91/codechobo
        ports:
        - containerPort: 8080
